apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenbin-test
  labels:
    tenbin-test
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     {{- include "tenbin-test.selectorLabels" . | nindent 6 }}
  template:
      # labels:
      #   {{- include "tenbin-test.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: helm-test21
          image: "ghcr.io/tsuyopon123/tenbin/tenbin:latest"
          imagePullPolicy: IfNotPresent
