apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenbin-deployment
spec:
  selector:
    matchLabels:
      app: tenbin
  replicas: 1
  template:
    metadata:
      labels:
        app: tenbin
    spec:
      containers:
      - name: tenbin
        image: ghcr.io/tsuyopon123/tenbin/tenbin:latest
        ports:
        - containerPort: 53