apiVersion: v1
kind: Service
metadata:
  name: tenbin-test
  # labels:
  #   tenbin-test
spec:
  type: application
  ports:
    - port: 53
      targetPort: dns
      protocol: UDP
      name: dns
  # selector:
  #   {{- include "tenbin-test.selectorLabels" . | nindent 4 }}
