apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenbin-test.fullname" . }}
  labels:
    {{- include "tenbin-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    {{- include "tenbin-test.selectorLabels" . | nindent 4 }}
